---
title: Disable sysfetch
description: Disables sysfetch when user has an SSD
actions:
    #Apply theme file and set recent themes
  - !powerShell:
    command: '.\DISABLESYSFETCH.ps1'
    wait: true
    exeDir: true
    onUpgrade: false
    runas: currentUserElevated