---
title: Disable Recall Snapshots
description: Disables snapshots of Recall (24H2+)
builds: [ '>=22000' ]
actions:
  - !cmd:
    command: '"AtlasDesktop\3. General Configuration\AI Features\Recall\Disable Recall Support (default).cmd" /silent'
    exeDir: true
    wait: true
    runas: currentUserElevated