---
title: Disable Mouse Acceleration
description: Disables mouse acceleration (also called 'Enhance Pointer Precision') for 1:1 mouse movement, which is what most gamers would want
actions:
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\Control Panel\Mouse'
    value: 'MouseSpeed'
    data: '0'
    type: REG_SZ
    
    
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\Control Panel\Mouse'
    value: 'MouseThreshold1'
    data: '0'
    type: REG_SZ
    
    
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\Control Panel\Mouse'
    value: 'MouseThreshold2'
    data: '0'
    type: REG_SZ
    
    
