---
title: Delete Windows-version Specific Tweaks
description: Deletes Windows 10 or Windows 11-only tweaks in the Atlas folder, depending on the current version
actions:
    # Delete ARM-specific files
    # FTH files (which are also non-ARM) are deleted in its own YML
  - !powerShell:
    command: |
      Remove-Item -Path """$([Environment]::GetFolderPath('Windows'))\AtlasDesktop\4. Interface Tweaks\Start Menu\*Open-Shell*""" -Force -Recurse
    wait: true
    cpuArch: 'Arm64'
