---
title: Configure Taskbar Pins
description: Configures taskbar pins for QoL, puts the browser first (if there is one) and Explorer next
onUpgrade: false
actions:
    # PowerShell commands used:
    # [BitConverter]::ToString($(Get-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband" -Name "FavoritesResolve").FavoritesResolve) -replace '-' | clip
    # [BitConverter]::ToString($(Get-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband" -Name "Favorites").Favorites) -replace '-' | clip

  - !taskKill: {name: 'explorer'}

    # Config pins
  - !registryKey:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'
  - !registryKey:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'
    operation: add
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'
    value: 'FavoritesVersion'
    data: '3'
    type: REG_DWORD
    scope: defaultUser
    
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband\AuxilliaryPins'
    value: 'MailPin'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband\AuxilliaryPins'
    value: 'CopilotPWAPin'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
    # Not sure what this does
  # - !registryValue:
  #   path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband\AuxilliaryPins'
  #   value: 'TFLPin'
  #   data: '0'
  #   type: REG_DWORD

# Sets a temporary value for taskbar pins after oobe
  - !registryValue: { path: 'HKLM\SOFTWARE\AtlasOS\TempKey', value: 'browser', data: "Brave", type: REG_SZ, option: 'browser-brave', oobe: only}
  - !registryValue: { path: 'HKLM\SOFTWARE\AtlasOS\TempKey', value: 'browser', data: "Firefox", type: REG_SZ, option: 'browser-firefox', oobe: only}
  - !registryValue: { path: 'HKLM\SOFTWARE\AtlasOS\TempKey', value: 'browser', data: "Google Chrome", type: REG_SZ, option: 'browser-chrome', oobe: only}
  - !registryValue: { path: 'HKLM\SOFTWARE\AtlasOS\TempKey', value: 'browser', data: "LibreWolf", type: REG_SZ, option: 'browser-librewolf', oobe: only}
  - !registryValue: { path: 'HKLM\SOFTWARE\AtlasOS\TempKey', value: 'browser', data: "", type: REG_SZ, option: 'browser-librewolf', oobe: only}

# Set new pins
  # TODO verify this all works. Can test by setting it up and restarting VM
  - !powerShell:
    command: ''Register-ScheduledTask -TaskName "TASKBARPINS" -Trigger (New-ScheduledTaskTrigger -AtStartup) -Action (New-ScheduledTaskAction -Execute "${Env:WinDir}\System32\WindowsPowerShell\v1.0\powershell.exe" -Argument "-WindowStyle Hidden -Command `"& 'C:\Windows\AtasModules\Scripts\taskbarPins.ps1'`"") -RunLevel Highest -Force;''
    option: '!install-another-browser'
    exeDir: true
  - !powerShell:
    command: "'Register-ScheduledTask -TaskName "TASKBARPINS" -Trigger (New-ScheduledTaskTrigger -AtStartup) -Action (New-ScheduledTaskAction -Execute "${Env:WinDir}\System32\WindowsPowerShell\v1.0\powershell.exe" -Argument "-WindowStyle Hidden -Command `"& C:\Windows\AtasModules\Scripts\taskbarPins.ps1 'Brave'`"") -RunLevel Highest -Force;'"
    option: 'browser-brave'
    exeDir: true
  - !powerShell:
    command: "'Register-ScheduledTask -TaskName "TASKBARPINS" -Trigger (New-ScheduledTaskTrigger -AtStartup) -Action (New-ScheduledTaskAction -Execute "${Env:WinDir}\System32\WindowsPowerShell\v1.0\powershell.exe" -Argument "-WindowStyle Hidden -Command `"& 'C:\Windows\AtasModules\Scripts\taskbarPins.ps1' 'Firefox'`"") -RunLevel Highest -Force;'"
    option: 'browser-firefox'
    exeDir: true
  - !powerShell:
    command: "'Register-ScheduledTask -TaskName "TASKBARPINS" -Trigger (New-ScheduledTaskTrigger -AtStartup) -Action (New-ScheduledTaskAction -Execute "${Env:WinDir}\System32\WindowsPowerShell\v1.0\powershell.exe" -Argument "-WindowStyle Hidden -Command `"& 'C:\Windows\AtasModules\Scripts\taskbarPins.ps1' 'Google Chrome'`"") -RunLevel Highest -Force;'"
    option: 'browser-chrome'
    exeDir: true
  - !powerShell:
    command: "'Register-ScheduledTask -TaskName "TASKBARPINS" -Trigger (New-ScheduledTaskTrigger -AtStartup) -Action (New-ScheduledTaskAction -Execute "${Env:WinDir}\System32\WindowsPowerShell\v1.0\powershell.exe" -Argument "-WindowStyle Hidden -Command `"& 'C:\Windows\AtasModules\Scripts\taskbarPins.ps1' 'Librewolf'`"") -RunLevel Highest -Force;'"
    option: 'browser-librewolf'
    exeDir: true
  - !run: {exe: 'explorer.exe', runas: 'currentUser', wait: false}
  #- !powerShell:
  #  command: 'Register-ScheduledTask -TaskName "TASKBARPINS" -Trigger (New-ScheduledTaskTrigger -AtStartup) -Action (New-ScheduledTaskAction -Execute "${Env:WinDir}\System32\WindowsPowerShell\v1.0\powershell.exe" -Argument "-WindowStyle Hidden -Command `"& 'C:\Windows\AtasModules\Scripts\taskbarPins.ps1' -`"") -RunLevel Highest -Force;'
