---
title: Disable Windows Chat
description: Disables Windows Chat as it's not commonly used
builds: [ '>=22000' ]
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Chat'
    value: 'ChatIcon'
    data: '3'
    type: REG_DWORD
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'TaskbarMn'
    data: '0'
    type: REG_DWORD
    
    
